version: '3'

services:
  collectd:
    image: fr3nd/collectd:5.5.0-1
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./config/collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb:1.5.4
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./config/types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:6.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./storage/grafana:/var/lib/grafana
    user: ${GRAFANA_USER_ID}

  prometheus:
    image: prom/prometheus:v2.10.0
    ports:
      - "9090:9090"
    volumes:
      - ${CURRENT_DIRECTORY}/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - '9100:9100'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    ports:
      - 9100:9100

  telegraf:
    image: telegraf:1.9.5
    ports:
      - '9273:9273'
    volumes:
      - ${CURRENT_DIRECTORY}/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

# for persistent data
volumes:
  influxdb_data:
  prometheus_data:
