version: '3'

services:
  graphite:
    environment:
        - COLLECTD=1
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:8080"
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always
  grafana:
    restart: always
    image: grafana/grafana:6.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./storage/grafana:/var/lib/grafana
    user: ${USER_ID}
    links:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password123
